(function(){
  'use strict';
  var TYPE_LABELS={current:'Current account',savings:'Savings account',joint:'Joint account',cash:'Cash account',investment:'Investment account',other:'Other'};
  var editingId=null;
  function state(){return window.state||null}
  function accounts(){var s=state();return s&&Array.isArray(s.accounts)?s.accounts:[]}
  function active(){var s=state();return accounts().find(function(a){return a.id===s.activeAccountId&&!a.archived})||accounts().find(function(a){return a.isDefault&&!a.archived})||accounts()[0]||null}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function uid(){return 'account-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
  function save(){var s=state();if(window.VeyraAccountsFoundation)window.VeyraAccountsFoundation.migrateState(s);if(typeof window.saveState==='function')window.saveState(s);window.dispatchEvent(new CustomEvent('veyra:accounts-changed',{detail:{activeAccountId:s.activeAccountId}}))}
  function typeLabel(t){return TYPE_LABELS[t]||TYPE_LABELS.other}
  function iconFor(t){return {current:'💳',savings:'🏦',joint:'👥',cash:'💶',investment:'📈',other:'👛'}[t]||'👛'}
  function renderSelector(){var a=active(),label=document.getElementById('accountSelectorLabel'),icon=document.getElementById('accountSelectorIcon'),list=document.getElementById('accountSelectorList');if(!label||!list)return;label.textContent=a?a.name:'Account';if(icon)icon.textContent=iconFor(a&&a.type);list.innerHTML=accounts().filter(function(x){return !x.archived}).map(function(x){return '<button class="account-choice'+(a&&x.id===a.id?' is-active':'')+'" type="button" data-account-select="'+esc(x.id)+'"><span class="account-choice-dot"></span><span class="account-choice-copy"><span class="account-choice-name">'+esc(x.name)+'</span><span class="account-choice-type">'+esc(typeLabel(x.type))+(x.isDefault?' · Default':'')+'</span></span></button>'}).join('')+'<div class="account-popover-sep"></div><button class="account-manage-link" type="button" data-all-accounts>All Accounts overview</button><button class="account-manage-link" type="button" data-account-transfers>Account transfers</button><button class="account-manage-link" type="button" data-account-manage>Manage accounts</button>'}
  function renderManager(){var list=document.getElementById('accountManagerList');if(!list)return;var rows=accounts();list.innerHTML=rows.map(function(a,i){var activeNow=state().activeAccountId===a.id;var canDelete=rows.length>1;return '<article class="account-manager-card'+(a.archived?' is-archived':'')+'"><div class="account-card-icon">'+iconFor(a.type)+'</div><div><div class="account-card-title"><strong>'+esc(a.name)+'</strong>'+(a.isDefault?'<span class="account-badge">Default</span>':'')+(activeNow?'<span class="account-badge">Selected</span>':'')+(a.archived?'<span class="account-badge">Archived</span>':'')+(a.visibility==='shared'?'<span class="account-badge account-badge-shared">🤝 Shared</span>':'')+'</div><div class="account-card-meta">'+esc(typeLabel(a.type))+' · '+esc(a.currency||'EUR')+'</div></div><div class="account-card-actions"><button class="account-icon-btn" type="button" data-account-up="'+esc(a.id)+'" '+(i===0?'disabled':'')+'>↑</button><button class="account-icon-btn" type="button" data-account-down="'+esc(a.id)+'" '+(i===rows.length-1?'disabled':'')+'>↓</button><button class="account-icon-btn" type="button" data-account-edit="'+esc(a.id)+'">Edit</button>'+(a.isDefault?'':'<button class="account-icon-btn" type="button" data-account-default="'+esc(a.id)+'" '+(a.archived?'disabled':'')+'>Set default</button>')+'<button class="account-icon-btn" type="button" data-account-archive="'+esc(a.id)+'">'+(a.archived?'Restore':'Archive')+'</button>'+(canDelete?'<button class="account-icon-btn account-delete-btn" type="button" data-account-delete="'+esc(a.id)+'">Delete</button>':'')+'</div></article>'}).join('')}
  function openManager(){document.getElementById('accountManagerModal').hidden=false;document.body.style.overflow='hidden';renderManager();hideEditor();setTimeout(function(){document.getElementById('accountManagerClose').focus()},0)}
  function closeManager(){document.getElementById('accountManagerModal').hidden=true;document.body.style.overflow='';hideEditor()}
  function fillSourceOptions(selected){var source=document.getElementById('accountSourceInput');if(!source)return;source.innerHTML=accounts().filter(function(a){return !a.archived}).map(function(a){return '<option value="'+esc(a.id)+'"'+(a.id===selected?' selected':'')+'>'+esc(a.name)+'</option>'}).join('')}
  function showEditor(id){editingId=id||null;var a=id?accounts().find(function(x){return x.id===id}):null;document.getElementById('accountEditorTitle').textContent=a?'Edit account':'Add account';document.getElementById('accountNameInput').value=a?a.name:'';document.getElementById('accountTypeInput').value=a?a.type:'current';document.getElementById('accountCurrencyInput').value=a?a.currency||'EUR':'EUR';var visInput=document.getElementById('accountVisibilityInput');if(visInput)visInput.value=a?(a.visibility||'private'):'private';var opts=document.getElementById('accountCopyOptions');if(opts)opts.hidden=!!a;fillSourceOptions(state().activeAccountId);document.getElementById('accountEditor').hidden=false;document.getElementById('accountNameInput').focus()}
  function hideEditor(){editingId=null;var el=document.getElementById('accountEditor');if(el)el.hidden=true}
  function commitEditor(){var name=document.getElementById('accountNameInput').value.trim(),type=document.getElementById('accountTypeInput').value,currency=document.getElementById('accountCurrencyInput').value,visInput=document.getElementById('accountVisibilityInput'),visibility=visInput&&visInput.value==='shared'?'shared':'private';if(!name){alert('Please enter an account name.');return}var duplicate=accounts().some(function(a){return a.id!==editingId&&a.name.toLowerCase()===name.toLowerCase()});if(duplicate){alert('An account with this name already exists.');return}if(editingId){var item=accounts().find(function(a){return a.id===editingId});if(item){item.name=name;item.type=type;item.currency=currency;item.visibility=visibility}}else{var id=uid();accounts().push({id:id,name:name,type:type,currency:currency,openingBalance:0,currentBalance:null,icon:'wallet',color:'',isDefault:false,includeInNetWorth:true,archived:false,visibility:visibility,createdAt:new Date().toISOString()});if(window.VeyraAccountBudgets){window.VeyraAccountBudgets.createForAccount(id,{mode:document.getElementById('accountSetupModeInput').value,sourceAccountId:document.getElementById('accountSourceInput').value})}}save();hideEditor();renderManager();renderSelector()}
  function selectAccount(id){var a=accounts().find(function(x){return x.id===id&&!x.archived});if(!a)return;if(window.VeyraAccountBudgets)window.VeyraAccountBudgets.switchAccount(id);else{state().activeAccountId=id;save()}renderSelector();closePopover()}
  function setDefault(id){var target=accounts().find(function(a){return a.id===id&&!a.archived});if(!target)return;accounts().forEach(function(a){a.isDefault=a.id===id});save();renderManager();renderSelector()}
  function toggleArchive(id){var a=accounts().find(function(x){return x.id===id});if(!a)return;var activeCount=accounts().filter(function(x){return !x.archived}).length;if(!a.archived&&activeCount<=1){alert('You need to keep at least one active account.');return}if(!a.archived&&a.isDefault){alert('Set another account as default before archiving this one.');return}a.archived=!a.archived;if(a.archived&&state().activeAccountId===a.id){var fallback=accounts().find(function(x){return x.isDefault&&!x.archived})||accounts().find(function(x){return !x.archived});if(fallback&&window.VeyraAccountBudgets)window.VeyraAccountBudgets.switchAccount(fallback.id);else state().activeAccountId=fallback&&fallback.id}save();renderManager();renderSelector()}
  function deleteAccount(id){var s=state(),a=accounts().find(function(x){return x.id===id});if(!a||accounts().length<=1)return;if(!confirm('Delete “'+a.name+'” and all budget data stored inside it? This cannot be undone.'))return;var fallback=accounts().find(function(x){return x.id!==id&&x.isDefault&&!x.archived})||accounts().find(function(x){return x.id!==id&&!x.archived})||accounts().find(function(x){return x.id!==id});if(!fallback)return;if(s.activeAccountId===id&&window.VeyraAccountBudgets)window.VeyraAccountBudgets.switchAccount(fallback.id);s.accounts=s.accounts.filter(function(x){return x.id!==id});if(a.isDefault){s.accounts.forEach(function(x){x.isDefault=x.id===fallback.id})}if(window.VeyraAccountBudgets)window.VeyraAccountBudgets.removeAccount(id);s.activeAccountId=fallback.id;save();renderManager();renderSelector();if(typeof window.render==='function')window.render()}
  function move(id,dir){var arr=accounts(),i=arr.findIndex(function(a){return a.id===id}),j=i+dir;if(i<0||j<0||j>=arr.length)return;var t=arr[i];arr[i]=arr[j];arr[j]=t;save();renderManager();renderSelector()}
  function closePopover(){var p=document.getElementById('accountSelectorPopover'),b=document.getElementById('accountSelectorBtn');if(p)p.classList.remove('is-open');if(b)b.setAttribute('aria-expanded','false')}
  document.addEventListener('click',function(e){var btn=e.target.closest('#accountSelectorBtn');if(btn){var p=document.getElementById('accountSelectorPopover'),will=!p.classList.contains('is-open');closePopover();if(will){p.classList.add('is-open');btn.setAttribute('aria-expanded','true')}return}var sel=e.target.closest('[data-account-select]');if(sel){selectAccount(sel.getAttribute('data-account-select'));return}if(e.target.closest('[data-account-manage]')){closePopover();openManager();return}if(e.target.closest('#accountManagerClose')||e.target.classList.contains('account-manager-backdrop')){closeManager();return}if(e.target.closest('#accountAddBtn')){showEditor(null);return}if(e.target.closest('#accountEditorCancel')){hideEditor();return}if(e.target.closest('#accountEditorSave')){commitEditor();return}var edit=e.target.closest('[data-account-edit]');if(edit){showEditor(edit.getAttribute('data-account-edit'));return}var def=e.target.closest('[data-account-default]');if(def){setDefault(def.getAttribute('data-account-default'));return}var arc=e.target.closest('[data-account-archive]');if(arc){toggleArchive(arc.getAttribute('data-account-archive'));return}var del=e.target.closest('[data-account-delete]');if(del){deleteAccount(del.getAttribute('data-account-delete'));return}var up=e.target.closest('[data-account-up]');if(up){move(up.getAttribute('data-account-up'),-1);return}var down=e.target.closest('[data-account-down]');if(down){move(down.getAttribute('data-account-down'),1);return}if(!e.target.closest('.account-switcher-block'))closePopover()});
  document.addEventListener('keydown',function(e){if(e.key==='Escape'){closePopover();if(!document.getElementById('accountManagerModal').hidden)closeManager()}if(e.key==='Enter'&&e.target&&e.target.id==='accountNameInput')commitEditor()});
  function init(){if(!state())return setTimeout(init,30);renderSelector()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());
